### ISSUE TITLE
Code for training seems incomplete?

### ISSUE THREAD

**Issue by erasaur** [veralauee/DPatch#2]
For instance, it seems like the training code doesn't apply the patch at all ([train.py:97](https://github.com/veralauee/DPatch/blob/master/train.py#L97) does not specify `attack` parameter to `net`). 

It's also not clear whether you were intending to modify the ground truth label in the [dataset](https://github.com/veralauee/DPatch/blob/master/datasets/pascal_voc.py#L174), since the bboxes are unmodified. (Training-wise this does not seem to matter as the ground truth is modified in [imdb.py:74](https://github.com/veralauee/DPatch/blob/master/datasets/imdb.py#L74) anyway.)

For context, I'm trying to reproduce the results in your paper with the default configurations in this repo (after fixing the `train.py` bug), but currently the fitted patch does not affect mAP very much -- similar mAP as compared to running `test.py` without applying any patch -- even after ~500k iterations and using a much larger patch (120x120) than the paper (20x20 to 80x80). The provided `untargetd_DPATCH.npy` has significantly lower mAP, but contains `inf` and `-inf` values -- it's unclear how those values surfaced given that the gradients for the patch seem generally pretty small. 

So I'm guessing my training setup went wrong somehow. Any pointers for setting up the repo for training a patch would be greatly appreciated!

**Comment by sheepdnb** [comment]
Any updates on this?

**Comment by littlekittel** [comment]
First of all the paper is really interesting and it would be great to apply the concept to different data sets.
Any chance to get support by the author?
Also struggling to reproduce the results of the paper.
Anyone managed to do so?

**Comment by XiaodanLi001** [comment]
> train.py:97

Hi, have you completed this training code? I have trained it with no codes changed, but the resulted patch cannot attack successfully. Do you have any suggestions ?

**Comment by XiaodanLi001** [comment]
> For instance, it seems like the training code doesn't apply the patch at all ([train.py:97](https://github.com/veralauee/DPatch/blob/master/train.py#L97) does not specify `attack` parameter to `net`).
> 
> It's also not clear whether you were intending to modify the ground truth label in the [dataset](https://github.com/veralauee/DPatch/blob/master/datasets/pascal_voc.py#L174), since the bboxes are unmodified. (Training-wise this does not seem to matter as the ground truth is modified in [imdb.py:74](https://github.com/veralauee/DPatch/blob/master/datasets/imdb.py#L74) anyway.)
> 
> For context, I'm trying to reproduce the results in your paper with the default configurations in this repo (after fixing the `train.py` bug), but currently the fitted patch does not affect mAP very much -- similar mAP as compared to running `test.py` without applying any patch -- even after ~500k iterations and using a much larger patch (120x120) than the paper (20x20 to 80x80). The provided `untargetd_DPATCH.npy` has significantly lower mAP, but contains `inf` and `-inf` values -- it's unclear how those values surfaced given that the gradients for the patch seem generally pretty small.
> 
> So I'm guessing my training setup went wrong somehow. Any pointers for setting up the repo for training a patch would be greatly appreciated!

Hi, have you completed this training code? I have trained it with no codes changed, but the resulted patch cannot attack successfully. Do you have any suggestions ?

**Comment by wpy16131034** [comment]
I didn't reproduce the result either...I think there might be something wrong with the paper


发自我的iPhone

------------------ Original ------------------

**Comment by erasaur** [comment]
Sorry for the late reply -- you have to normalize the gradients in order for the attack to work. However, the DPatch approach has significant limitations, namely it produces patches that are not physically printable (since the pixel values are unclipped, thus resulting in the `inf` and `-inf` mentioned in my first post). I recently published a paper elaborating on these issues and proposing an alternate attack that is more effective in both digital and physical space. You can read the details here: https://arxiv.org/abs/1906.11897.

**Comment by XiaodanLi001** [comment]
> Sorry for the late reply -- you have to normalize the gradients in order for the attack to work. However, the DPatch approach has significant limitations, namely it produces patches that are not physically printable (since the pixel values are unclipped, thus resulting in the `inf` and `-inf` mentioned in my first post). I recently published a paper elaborating on these issues and proposing an alternate attack that is more effective in both digital and physical space. You can read the details here: https://arxiv.org/abs/1906.11897.

Ermmm, so, you have reproduced this work? Yesterday I got some troubles for training. I added the attack to make patch applied. But it occures some troubles: RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation. Do you have any suggestions? By the way, are you going to release your code for https://arxiv.org/abs/1906.11897?

**Comment by XiaodanLi001** [comment]
> I didn't reproduce the result either...I think there might be something wrong with the paper 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: XiaodanLi001 <notifications@github.com> Date: Thu,Aug 15,2019 9:56 PM To: veralauee/DPatch <DPatch@noreply.github.com> Cc: wpy16131034 <285671968@qq.com>, Manual <manual@noreply.github.com> Subject: Re: [veralauee/DPatch] Code for training seems incomplete? (#2) For instance, it seems like the training code doesn't apply the patch at all (train.py:97 does not specify attack parameter to net). It's also not clear whether you were intending to modify the ground truth label in the dataset, since the bboxes are unmodified. (Training-wise this does not seem to matter as the ground truth is modified in imdb.py:74 anyway.) For context, I'm trying to reproduce the results in your paper with the default configurations in this repo (after fixing the train.py bug), but currently the fitted patch does not affect mAP very much -- similar mAP as compared to running test.py without applying any patch -- even after ~500k iterations and using a much larger patch (120x120) than the paper (20x20 to 80x80). The provided untargetd_DPATCH.npy has significantly lower mAP, but contains inf and -inf values -- it's unclear how those values surfaced given that the gradients for the patch seem generally pretty small. So I'm guessing my training setup went wrong somehow. Any pointers for setting up the repo for training a patch would be greatly appreciated! Hi, have you completed this training code? I have trained it with no codes changed, but the resulted patch cannot attack successfully. Do you have any suggestions ? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Hi, can we add wechat for discussing it?

**Comment by XiaodanLi001** [comment]
> > Sorry for the late reply -- you have to normalize the gradients in order for the attack to work. However, the DPatch approach has significant limitations, namely it produces patches that are not physically printable (since the pixel values are unclipped, thus resulting in the `inf` and `-inf` mentioned in my first post). I recently published a paper elaborating on these issues and proposing an alternate attack that is more effective in both digital and physical space. You can read the details here: https://arxiv.org/abs/1906.11897.
> 
> Ermmm, so, you have reproduced this work? Yesterday I got some troubles for training. I added the attack to make patch applied. But it occures some troubles: RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation. Do you have any suggestions? By the way, are you going to release your code for https://arxiv.org/abs/1906.11897?

sorry, I found the mistake was caused by batch_size. If I set the batch_size>1, it went wrong.

**Comment by XiaodanLi001** [comment]
> Sorry for the late reply -- you have to normalize the gradients in order for the attack to work. However, the DPatch approach has significant limitations, namely it produces patches that are not physically printable (since the pixel values are unclipped, thus resulting in the `inf` and `-inf` mentioned in my first post). I recently published a paper elaborating on these issues and proposing an alternate attack that is more effective in both digital and physical space. You can read the details here: https://arxiv.org/abs/1906.11897.

Thank you so much for your reply. I have read your paper this morning in detail and thank you a lot for your contributions. About this, I still have some questions. First of all, I added "attack = 'untarget'" and start training. The mAP seems to degrade slightly(loss=0.05, 50epoch, mAP=40.99%). Secondly, I tried to normalize the gradient of net.patch by add 'torch.nn.utils.clip_grad_norm(net.parameters(),1,'inf') to clip grad into [0,1] (after loss.backward(), before optimizer.step()). (loss=0.08, 34 epoch,mAP=42.59%). I have some questions.
1.  In your paper, it writes after 50epochs DPatch can attack with good results.  I was wondering if I missed some steps (such as gt processing or something as you wrote in this topic)
2. When testing, which model did you applied? The original yolo-voc.weights.h5 or generated darknet19_voc07traincal_exp3_xx.h5? I think there's no difference between them , but they generate different result. Do you have any pointers about it?
3. I'm still confused of the way you normalize the gradients. Can you share some details?

Again, thank you so much for your reply. Once I reproduced DPatch, I will try to reproduce your paper and cite it. Looking forward to your reply.

**Comment by adbedada** [comment]
@XiaodanLi001 have you had any luck reproducing DPatch?

**Comment by adbedada** [comment]
@erasaur Do you have a working repo of DPatch or its variant you can share? any help is appreciated!

**Comment by XiaodanLi001** [comment]
> @XiaodanLi001 have you had any luck reproducing DPatch?

No, and this is a huge bug in this repo. According to the training code, though all the parameters won't be updated since their learning rates are 0s. But the batch_norm.running_mean will change. And once I fixed this bug, the mAP will drop as much as the unfixed codes. I have wrote to the authors but no response back.

**Comment by adbedada** [comment]
@XiaodanLi001 Thanks for getting in touch. It's annoying. I'm also curious to know how @erasaur managed to get the results he mentioned on his paper (https://arxiv.org/abs/1906.11897). He used DPatch to benchmark his version of adversarial attack.

**Comment by hoopool** [comment]
@erasaur could you share the code about this paper (https://arxiv.org/abs/1906.11897) on github, so that we can learn how it work exactly, so appreciated~

**Comment by quahez** [comment]
anybody has an updated code or a new repo to reference for Dpatch?

Thanks!

**Comment by quahez** [comment]
I did something extreme with the original code by resizing the patch w and h to 1. (config.py:L90) and it gave me a result of 0.082 (vs 0.0866 for 120 x 120). This is unbelievable as I wouldn't expect a 1 x 1 pixel attack to cause such a huge effect and even outperforming a 120 x 120 patch.
